@echo off
set "WL_APP_NAME=B-Lite Management"
set "WL_APP_VERSION=6.0"
set "WL_APP_PUBLISHER=B-Lite Technologies"
set "WL_EXE_NAME=BLiteManagement"
set "WL_EXE_FILE=BLiteManagement.exe"
set "WL_DIST_NAME=BLiteManagement"
set "WL_INSTALL_DIR_NAME=BLiteManagement"
set "WL_INSTALLER_NAME=BLiteManagement_Setup_v5.6.exe"
set "WL_APP_ICON=G:\chimmu\Bobys_Salon Billing\B-Lite management_Billing_V6.0\icon.ico"
set "WL_APP_ICON_NAME=icon.ico"
set "WL_INSTALLER_ICON=G:\chimmu\Bobys_Salon Billing\B-Lite management_Billing_V6.0\icon.ico"
set "WL_INSTALLER_ICON_NAME=icon.ico"
set "WL_RUNTIME_DIR_NAME=BLiteManagement"
set "WL_APPDATA_DIR_NAME=BLiteManagement_Data"
